### PR TITLE
several fixes

### PR DESCRIPTION
**Pull request by davidchase**
This PR addresses several issues.

- [x] Adds shrink-wrap to lock down dependencies for babel 
- [x] Wired up both rest & clear output buttons, ht @buzzdecafe 
- [x] Updates index.html to support handlebars for when updating the ramda versions using the Makefile
- [x] Adds Ramda to local scope to allow in order to avoid needing to type `R` followed by method name, ht @raine (had to hack around a bit so errors are not too verbose)

### CODE REVIEW

**Comment by CrossEye** [comment]
I've never worked with shrink-wrap.  It's not quite clear to me what it's for.

Other than that, this looks great!

**Comment by davidchase** [comment]
So the shrink-wrap let me lockdown all of the dependencies (specifically my case `bablyon`) to a specific version because otherwise when i tried to bundle the code... i would get babel errors such as missing `parser` etc. The shrink-wrap allows me to find all dependencies that use `babylon` and tell it to only use version `6.3.26` for example.

**Comment by CrossEye** [comment]
Makes sense.  I'm really looking forward to not having to use `R.whatever`.

This looks good to me.  :herb:

Anyone else have comments?

**Comment by davidchambers** [comment]
I'm comfortable deferring to @davidchase on this. :)

**Comment by buzzdecafe** [comment]
:cow2:

**Pull request merged**
