### PR TITLE
Closes #100, link to gitter

### LINKED ISSUE #100: Proposal: Add link to gitter room in top nav
^^^ any interest in this?

### PR DESCRIPTION
**Pull request by buzzdecafe**

### CODE REVIEW

**Comment by craigdallimore** [comment]
Hello @buzzdecafe 

#100 is just about adding a link to gitter right? That is indeed present and working. :+1: 

There is more that that in this changeset -  I presume there is a fair degree of automation going on. 

In index.html I can see many changes that look like this:

```diff
                 <div class="details panel panel-default">
                     <ul class="list-group">
                         <li class="list-group-item">
-                            <span class="type">Number</span>
+                            <span class="type">
+                            </span>
                             <span class="name">a</span>
                             <span class="description"></span>
                         </li>
                         <li class="list-group-item">
-                            <span class="type">Number</span>
+                            <span class="type">
+                            </span>
                             <span class="name">b</span>
                             <span class="description"></span>
                         </li>
```

... where the _type_ is no longer present. I'm not sure if this is intentional or not. Here is how it looks:

## Before:

before

## After:

after

There is also a collection of changes to the gitbook that I'm not sure are intentional:

## Before:

bef

## After:

aft

**Comment by buzzdecafe** [comment]
hmmm, yeah, too much unintentional stuff in there. thanks for the review, let me see if i can fix that. it shouldn't be this hard to add a link to the header :-)

**Comment by CrossEye** [comment]
I wouldn't worry overmuch about the Gitbook changes.  There's probably a different version of Gitbook generating the two outputs, and since we're not promoting this manually (nor even proceeding with it at the moment) I wouldn't worry about inconsistencies just yet.


Of course these other things do count...

**Comment by buzzdecafe** [comment]
going to take another run at this after gitbook is moved out

**Pull request closed without merging**
