### PR TITLE
try in repl update

### PR DESCRIPTION
**Pull request by davidchase**
updated the code for "Try in Repl" ... if you rebuild the docs with the `VERSION=0.19.0 make`  or whatever you guys use this should show a little "Try in Repl" button on the code snippets in the docs

i gave a shot in a separate branch and seems to work :smile:

### CODE REVIEW

**Comment by davidchase** [comment]
also added a `hidden` class on the textbox which should remove the white flash on load

**Comment by davidchambers** [comment]
> also added a `hidden` class on the textbox which should remove the white flash on load

Great!

Would you mind squashing the commits? (It's a little tricky now that there's a merge commit.)

**Comment by davidchase** [comment]
@davidchambers did you want me to squash the `merge` with `small fixes` as well ? because the changes are sort of trivial and it maybe easier for me to close the PR and open a new fresh one...

**Comment by davidchambers** [comment]
> did you want me to squash the `merge` with `small fixes` as well ?

Ideally, yes.

Rather than open a new pull request, you should be able to follow the steps I suggested in https://github.com/ramda/ramda/pull/1571#issuecomment-168410352. You'll need to use the appropriate branch names, of course. :)

**Comment by davidchase** [comment]
@davidchambers thanks for the suggestion but based on the comments and my several attempts to do so... nothing worked.. primarily the patch wasnt working
kept getting cant find file to patch.

**Comment by davidchambers** [comment]
Here you go: https://github.com/davidchambers/ramda.github.io/compare/master...davidchase

Run these commands to update this pull request:

```console
$ git reset --hard b2d90e4417c5d7da6c74b8a1ea50317c1dcafd01
$ git pull git@github.com:davidchambers/ramda.github.io.git davidchase
$ git commit --amend  # make yourself the committer
$ git push origin master --force
```

I strongly recommend working on feature branches in future. ;)

**Comment by branneman** [comment]
... and updating your fork with `rebase`, not `merge` :)

**Comment by davidchase** [comment]
@davidchambers thanks for the tips and i will feature branch from now on :+1:

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
Updated the docs with this.  It's looking great.  There is one minor bug, which I can't track down right now as I've off to my volleyball match.  The version number in the header of the REPL is still saying 0.19.0, whereas the others are at 0.19.1.  I assume something in the build script is updating the headers, but never needed to do the REPL before.

Very nice job, @davidchase!

**Comment by davidchase** [comment]
i can look into that :smile:

**Pull request merged**
