### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by vyorkin**
fix typo for whereEq doc

### CODE REVIEW

**Comment by buzzdecafe** [comment]
we should also fix this in the source at ramda/ramda or it will be back nxt time we publish and generate docs.

**Comment by davidchambers** [comment]
> we should also fix this in the source at ramda/ramda or it will be back next time we publish and generate docs.

@vikfroberg made this fix in ramda/ramda#1084.

**Comment by buzzdecafe** [comment]
we gotta get 0.15 out :-)

**Comment by vyorkin** [comment]
:+1:

**Pull request closed without merging**
