### PR TITLE
include @since, @typedefn, and additional @sig annotations

### PR DESCRIPTION
**Pull request by davidchambers**
Dependent on #34, which I will merge before merging this pull request.

@CrossEye, please run `VERSION=0.18.0 make` to see whether you are happy with the following:

  - the styling of type signatures;
  - the handling of functions with multiple type signatures (see `R.take`, for example);
  - the styling of type definitions (see `R.view`, for example);
  - the links for toggling the visibility of parameter details; and
  - the rendering of `@since` annotations.

I'll admit that the design looks a bit like a dog's breakfast with these additions, but this shouldn't prevent us from making useful content available to users. Presenting this content in a sensible manner will require time and thought from a designer such as @ricburton.

### CODE REVIEW

**Comment by CrossEye** [comment]
I'm sorry, I ran and published the docs based on what was in HEAD.  I am going to bed now, but I will make a point of looking at this tomorrow.  We can always overlay the published docs.

**Comment by CrossEye** [comment]
Ok, never mind, I had to look before going to be.  :smile:

I'm reasonably happy with these, although not thrilled with them, except for the the styling of the type signatures, both single and multiple.  Those look perfect to me.

>  - the styling of type definitions (see `R.view`, for example);

I think this is a reasonable first pass, but I believe for the longer haul, we should be maintaining a separate types list, and these should just offer links to that list, perhaps ones that can be merged into this single page in a bottom section.  If we got really smart, that entry could link back to all the functions that had references to the type.  This is longer-term, meaning I don't plan on trying this any time soon.

>  - the links for toggling the visibility of parameter details; and

I would really prefer an icon for this to text.  It's ok as is, but I think an icon is less intrusive, and cuts down on the wall-of-text that's too easy to build up.  This

>  - the rendering of `@since` annotations.

Again, these are ok, but I think they would be better placed underneath the categories and source-code links.  They are both more prominent and less intrusive there.

If we don't get someone with decent design skills stepping up soon for these, I will probably take a swing at these last two sometime in the reasonably near future.  But I would much rather have someone who's good at this. 


> I'll admit that the design looks a bit like a dog's breakfast with these additions, but this shouldn't prevent us from making useful content available to users. 

It's not that bad.  And I agree that we should do this sooner rather than later.  I would be all for doing this right away as is, and approaching any fixes as we get them.  If we can re-publish v0.18.0 easily enough now, then we no longer need to delay doc changes until a later release.

> Presenting this content in a sensible manner will require time and thought from a designer such as @ricburton.

Yes, but until someone with those skills volunteers, we'll do the best we can.

**Comment by branneman** [comment]
Is there a reason why this is not merged yet?

**Comment by CrossEye** [comment]
> Is there a reason why this is not merged yet?

Lethargy.

**Pull request merged**
