### PR TITLE
append is already taken and will not work in REPL

### PR DESCRIPTION
**Pull request by GantMan**
renamed `append` function to `appender`, works in REPL

### CODE REVIEW

**Comment by GantMan** [comment]
TL:DR;  This is what exists [Failing REPL](http://ramdajs.com/repl/#?code=var%20digits%20%3D%20%5B%271%27%2C%20%272%27%2C%20%273%27%2C%20%274%27%5D%3B%0Avar%20append%20%3D%20%28a%2C%20b%29%20%3D%3E%20%5Ba%20%2B%20b%2C%20a%20%2B%20b%5D%3B%0A%0AR.mapAccum%28append%2C%200%2C%20digits%29%3B)
And this is what is proposed: [Fixed REPL](http://ramdajs.com/repl/#?code=var%20digits%20%3D%20%5B%271%27%2C%20%272%27%2C%20%273%27%2C%20%274%27%5D%3B%0Avar%20appender%20%3D%20%28a%2C%20b%29%20%3D%3E%20%5Ba%20%2B%20b%2C%20a%20%2B%20b%5D%3B%0A%0AR.mapAccum%28appender%2C%200%2C%20digits%29%3B)

**Comment by buzzdecafe** [comment]
well spotted -- we have to fix that in the source as well. thanks

**Comment by GantMan** [comment]
I'll happily fix it in source.  Can you quick link me?

**Comment by buzzdecafe** [comment]
Thanks again -- this is where it's is from:

https://github.com/ramda/ramda/blob/master/src/mapAccum.js

**Comment by GantMan** [comment]
:+1:

**Pull request merged**
