### PR TITLE
adds-symbols - initial commit

### PR DESCRIPTION
**Pull request by thurt**
original issue: https://github.com/ramda/ramda/issues/1776

the complementary PR for ramda/ramda: https://github.com/ramda/ramda/pull/1852

### CODE REVIEW

**Comment by thurt** [comment]
There is a problem to be resolved: I don't think `custom.css` is being added during the make process. I'm not sure how to edit the makefile to make that happen?

I have been copying `custom.css` to the version folder after the make process.

**Comment by buzzdecafe** [comment]
looks like `custom.css` was added by you in https://github.com/ramda/ramda.github.io/issues/80

can that be made a `.less` file, rather than an extra css file? then `make` would just pick it up when it compiles the `.less` stuff

**Comment by thurt** [comment]
Thanks I'm not familiar with LESS and I totally missed that build step. Let me know if there is a better way to integrate the `custom.less` changes than what I have in the current commit.

Also I wanted to note that since these PRs are split between two repos I have been working locally with a modified make file:
```
$(VERSION)/docs/dist/ramda.js:
	mkdir -p '$(@D)'
	#curl --silent 'https://raw.githubusercontent.com/ramda/ramda/v$(VERSION)/dist/ramda.js' >'$@'
       # I modified this ramda.js to have the @symb changes for testing locally
	cp docs/dist/ramda.js '$@'
```
I assumed that once both of the PRs are merged, the curl address will have the new changes built into ramda.js?

**Comment by buzzdecafe** [comment]
> I assumed that once both of the PRs are merged, the curl address will have the new changes built into ramda.js?

Looks like the `@symb` stuff has not yet been merged over in ramda/ramda? once the `@symb` tags are there, i think it should "just work" next time ramda is released. I'll try and take a look at this tonight; can you send me your modified ramda.js so I can see it action?

**Comment by thurt** [comment]
> once the @symb tags are there, i think it should "just work" next time ramda is released.

Yep that's what I assume would happen.

Here's the `ramda.js` I am using to test, which works fine. It only includes symbol tags on R.adjust and R.mapAccum. I am running `VERSION=0.21.0 make` at command line.
https://gist.github.com/a1f4629fc848349f1b90ebd01d702894.git

Side Note: so in ramda/ramda I just tried rebuilding `ramda.js` with `npm run build`, which works fine and the file looks correct with all the symbol tags. But I get a makefile error when I try to use that file in a ramda.github.io build.
```
thurt@carrot:~/code/github/ramda.github.io$ VERSION=0.22.0 make
mkdir -p '0.22.0/tmp'
curl --silent 'https://raw.githubusercontent.com/ramda/ramda/v0.22.0/README.md' >'0.22.0/tmp/README.md'
mkdir -p '0.22.0/tmp'
curl --silent 'https://raw.githubusercontent.com/ramda/ramda/v0.22.0/package.json' >'0.22.0/tmp/package.json'
mkdir -p '0.22.0/docs/dist'
cp docs/dist/ramda.js '0.22.0/docs/dist/ramda.js'
VERSION='0.22.0' node_modules/.bin/jsdoc \
  --destination '0.22.0' \
  --template 'jsdoc' \
  '0.22.0/docs/dist/ramda.js'

/home/thurt/code/github/ramda.github.io/jsdoc/publish.js:31
  for (var idx = 0; idx < xs.length; idx += 1) {
                            ^

TypeError: Cannot read property 'length' of undefined
    at valuesForTitle (/home/thurt/code/github/ramda.github.io/jsdoc/publish.js:31:29)
    at simplifyData (/home/thurt/code/github/ramda.github.io/jsdoc/publish.js:62:57)
    at Array.map (native)
    at Object.exports.publish (/home/thurt/code/github/ramda.github.io/jsdoc/publish.js:122:12)
    at Object.module.exports.cli.generateDocs (/home/thurt/code/github/ramda.github.io/node_modules/jsdoc/cli.js:443:18)
    at Object.module.exports.cli.processParseResults (/home/thurt/code/github/ramda.github.io/node_modules/jsdoc/cli.js:394:13)
    at module.exports.cli.main (/home/thurt/code/github/ramda.github.io/node_modules/jsdoc/cli.js:236:14)
    at Object.module.exports.cli.runCommand (/home/thurt/code/github/ramda.github.io/node_modules/jsdoc/cli.js:192:5)
    at /home/thurt/code/github/ramda.github.io/node_modules/jsdoc/jsdoc.js:182:13
    at Object.<anonymous> (/home/thurt/code/github/ramda.github.io/node_modules/jsdoc/jsdoc.js:184:3)
Makefile:60: recipe for target '0.22.0/docs/index.html' failed
make: *** [0.22.0/docs/index.html] Error 1
```

**Comment by buzzdecafe** [comment]
that error is jsdoc choking on documentation in 0.22 that it doesn't know how to parse.

**Comment by davidchambers** [comment]
Does `VERSION=0.22.1 make` work?

**Comment by buzzdecafe** [comment]
it should -- that's how i published the docs. and that was the sole reason for the .1 patch release

**Comment by thurt** [comment]
> Does VERSION=0.22.1 make work?

Confirmed works!

**Comment by buzzdecafe** [comment]
i'm happy to merge this one :dromedary_camel:

**Pull request merged**
