### PR TITLE
Correct includes version

### LINKED ISSUE #223: R.includes "Added in v..." is inaccurate
Expected: ```Added in v0.26.0```
Actual: ```Added in v0.1.0```

Affects:

- 0.26.0/docs/index.html
- 0.26.1/docs/index.html

### PR DESCRIPTION
**Pull request by FruityFreedom**
resolves #223

### CODE REVIEW

**Comment by CrossEye** [comment]
I wonder if we should add something like

```
  @renamedFrom includes
```

 to keep the tracing clearer.

**Comment by Bradcomp** [comment]
This has been fixed in the master branch of Ramda: https://github.com/ramda/ramda/blob/master/source/includes.js#L11

Once we build a new version this will be updated automatically.

**Comment by jonlw** [comment]
Yes @CrossEye, I like the idea of ```@renamedFrom``` 

It can benefit someone who has learned Ramda with versions after a function rename, and now has a need to work with earlier versions.

**Comment by jonlw** [comment]
Thank you @Bradcomp 

My concern is the comment at ramda repo tags cannot be modified to resolve the inaccuracies in the 0.26.0 & 0.26.1 docs. Am I understanding this wrong?

It did feel dirty editing JSDoc output.

**Comment by FruityFreedom** [comment]
Closed re @Bradcomp comment.

This information is controlled from Ramda master

**Pull request closed without merging**
