### PR TITLE
replace ramda repl with ramtuary based repl

### PR DESCRIPTION
**Pull request by davidchase**
Preview it here: https://rawgit.com/davidchase/ramda.github.io/master/repl/index.html

Let me know what I can do next, i will be willing to iterate on it :smile:

### CODE REVIEW

**Comment by johnmichel** [comment]
:+1: :tada:

**Comment by CrossEye** [comment]
This is great!

If nobody objects, I'd like to put this onto the site, temporarily under a different URL than our current repl, perhaps http://ramdajs.com/try/.

There are two things that I'd like to see if we can do before replacing the old one.  First, and this may just be a matter of where this repl is hosted, the link shortener is not working, at least it didn't in  a few tests for me.  Second, I'd really like to skin this so that it looks simply like one more tab on the home page alongside Home, Documentation, and Github.  It's only that header bar that I care about here.  It would be nice to make the user feel she's staying on our pages.

**Comment by davidchase** [comment]
@CrossEye  Hows that ?

screen shot 2016-01-14 at 7 40 59 pm



Also what do you think if i update the handlebars to include to `Try in repl` from the docs ?

screen shot 2016-01-14 at 7 44 35 pm

I will fix the shortlink as well

**Comment by CrossEye** [comment]
This is great.  Thanks for the excellent work!

**Comment by buzzdecafe** [comment]
hell yeah

**Comment by CrossEye** [comment]
Definitely like the "Try in REPL" links.  That was one of the reasons I'd love to respond to `//=>`.

This is friggin' awesome!

**Comment by buzzdecafe** [comment]
> If nobody objects, I'd like to put this onto the site,

nobody objects.

**Comment by davidchambers** [comment]
Great work, @davidchase!

**Comment by davidchase** [comment]
thanks guys!

quick question after i update the docs to include `Try in REPL` do i just run `VERSION=0.19.0 make` and thats it?

**Comment by CrossEye** [comment]
@davidchase: Yes, that should do it.

**Comment by davidchase** [comment]
@CrossEye  running the above command removed some fonts?? and added a `0.19.0/tmp` directory and removed some `woff` fonts... seems a bit odd

let me know if anything needs adjustment I added the short link to point to `ramdajs.com/try` you can ping me directly on gitter as well if that is easier

**Comment by davidchase** [comment]
it seems to have more issue then needed... so i closed this and will open a new one hopefully with everything squared away

**Comment by davidchase** [comment]
re-opened in #45

**Pull request closed without merging**
