### PR TITLE
updated repl and added try in repl in docs

### PR DESCRIPTION
**Pull request by davidchase**
this should do it... i think the last PR i was commiting the results of my updates + `VERSION=0.19.0 make`

### CODE REVIEW

**Comment by buzzdecafe** [comment]
looks real good on my machine. Thanks very much for your work on this. This REPL is a huge improvement, and I am excited to get it out there.

**Comment by davidchase** [comment]
@buzzdecafe thanks and thank you for such a great library :smile:

**Comment by CrossEye** [comment]
I trust @buzzdecafe on this.  My head is too stuffed up to even try looking.  I'm very excited to see this when my brain is less foggy, though.

**Comment by davidchase** [comment]
@buzzdecafe @CrossEye i think the shortlink points to ramdajs.com/try instead of the ramdajs.com/repl because i was under the assumption that it is where it was going to go temporarily

let me know if you want me to update that real quick....

**Comment by CrossEye** [comment]
Yes, please.

I actually merged by accident.  Fat fingers on my phone.  When it asked for confirmation, I just said "Why not".  

As I said, foggy brained at the moment.

**Comment by davidchase** [comment]
no worries... updated #46

**Comment by buzzdecafe** [comment]
:tada: 

thanks! looks great

**Pull request merged**
