### PR TITLE
Replace REPL

### PR DESCRIPTION
**Pull request by craigdallimore**
Hello again

This is take 2 :clapper: at integrating the standalone repl as the _Try Ramda_ REPL.
Here is an [example hosted on github](https://craigdallimore.github.io/ramda.github.io/repl/) using  cdn.rawgit.com to host the bundled CSS and JS, and configured to use wzrd.in and jsdelivr to source the `sanctuary`, `ramda-fantasy` and `ramda` files.

Since last time we've added messaging (if one of the sourced files fails to load) and some layout / theme modifications.

I don't know if there is any way to stage these changes?

Relates to [#18](https://github.com/ramda/repl/issues/18).

### CODE REVIEW

**Comment by buzzdecafe** [comment]
looks a little weird on my machine:

Firefox:
screenshot_20161019_170757

Chromium:
screenshot_20161019_170833

**Comment by craigdallimore** [comment]
That is weird. I tested on Firefox dev edition too. Can you tell me the
version / OS?

**Comment by buzzdecafe** [comment]
Kubuntu 16.04; FF 51.0a2 (2016-10-13) (64-bit)

I'm gonna poke around in the styles and see if anything jumps out

**Comment by buzzdecafe** [comment]
nm, looks like there were some merge artifacts in my branch for some reason. now it is looking good!


`

**Comment by buzzdecafe** [comment]
i wanna give this another look-over tonight, but i'm confident.

**Comment by craigdallimore** [comment]
Please take as much time as you need, I respect that there is a lot of change here.

**Comment by buzzdecafe** [comment]
🎆 

excellent job. Looks great.

**Pull request merged**
