### PR TITLE
repl: apply R.toString to output value

### PR DESCRIPTION
**Pull request by davidchambers**
Closes ramda/ramda#1040

### CODE REVIEW

**Comment by buzzdecafe** [comment]
:cow2: :cow2:

**Comment by davidchambers** [comment]
How do we go about publishing this change without waiting for v0.15.0? If we merge this pull request will the change take effect immediately? Have I updated the correct files?

**Comment by buzzdecafe** [comment]
> If we merge this pull request will the change take effect immediately? 

yes. the repl is independent of the version publishing process.

**Comment by davidchambers** [comment]
Great! Shall we merge? :)

**Comment by buzzdecafe** [comment]
absolutement

**Comment by buzzdecafe** [comment]
looks *much* better!

**Pull request merged**
