### PR TITLE
search and filtering improvements (also fixes #188)

### LINKED ISSUE #188: Filter by type
e.g. click on function type `Logic` -> site showing only functions of `Logic` type

### PR DESCRIPTION
**Pull request by remmycat**
Now we will Filter content as well (resets filter when clicking on a function-link that isn't visible) and always scroll to top while typing.
Filtering content hugely increases usability for me, so that i can scroll through all list functions or similar stuff.

(Now in a feature branch)

### CODE REVIEW

**Comment by buzzdecafe** [comment]
First, thanks for taking this on. The search/filter could use some TLC. 

The category match is a bit surprising to me. If I type "mat" I get
image

but if I type "math" i get:
image

Shouldn't "mat" results include those that match "math"?

**Comment by buzzdecafe** [comment]
Aside to @MattMS: I take it pug templates are not wired up yet. This is another PR that tweaks the mustache tpls just a bit. What would it take to replace mustache with pug?

**Comment by MattMS** [comment]
The Pug templates should be able to be used, but I'll double check them.

The template changes in this appear very minimal, so should be easy to change to Pug from my quick look.

One option would be to merge this PR and then I can make a PR after that changes Pug to match.

**Comment by remmycat** [comment]
Sorry that I never followed up on this… 6 years ago?! Gonna close this - I don't really remember what I was doing here and if it's still needed. But anyone can feel free to take this over / finish this if they want to.

**Pull request closed without merging**
