### PR TITLE
Fixes #48: wire up reset button

### LINKED ISSUE #48: Repl Reset Button Does Nothing
Suggested behavior: `window.location = '/repl/'`

### PR DESCRIPTION
**Pull request by buzzdecafe**

### CODE REVIEW

**Comment by davidchambers** [comment]
What does the reset button do?

**Comment by buzzdecafe** [comment]
clears the repl. so this would also reset the url (i.e. remove the hash). But the fact that you had to ask makes me think maybe we need a better term than "Reset"; maybe "Clear REPL" or something?

**Comment by davidchambers** [comment]
Why not simply <kbd>⌘</kbd>-<kbd>A</kbd>, <kbd>⌫</kbd>? Clearing a textarea shouldn't require a custom UI element.

**Comment by buzzdecafe** [comment]
that sounds like a separate PR. At present, we have a button there wired to nothing.

**Comment by davidchambers** [comment]
All I'm suggesting is removing the button. :)

**Comment by davidchase** [comment]
doh! sorry about that

**Comment by CrossEye** [comment]
Should this button also clear the output console?  I've noticed that this REPL reports both the output of the last expression and the values sent to `console.log`.  But the latter are not cleared when the text content is removed.  Is the ability to do that -- which might be important -- a good reason for keeping this button?

**Comment by davidchase** [comment]
i have a `clear output` button... which works on ramtuary but for some reason doesnt work on this REPL... :disappointed:

**Comment by buzzdecafe** [comment]
one advantage of `location.href = '.'` is that the back button works. Not so for manually clearing it.

**Comment by buzzdecafe** [comment]
superseded by #58

**Pull request closed without merging**
