### PR TITLE
REPL: Get code param from hash part of URL

### LINKED ISSUE #102: REPL doesn't respect `code` query parameter anymore
@kujon observed:

>Refreshing the page clears it.
>
>Chrome 52.0.2743.116 (64-bit)
>OS X 10.11.6
>
>@ codemirror.min.js:1 Uncaught TypeError: Cannot read property 'split' of undefinedH.splitLines
>@ codemirror.min.js:1splitLines
>@ codemirror.min.js:1(anonymous function)
>@ codemirror.min.js:1(anonymous function)
>@ codemirror.min.js:1(anonymous function)
>@ codemirror.min.js:14../googl
>@ bundle.js:251s
>@ bundle.js:1e
>@ bundle.js:1(anonymous function)
>@ bundle.js:1

### PR DESCRIPTION
**Pull request by fix-fix**
Previously it was trying to get querystring from the complete URL, so for path like `/path?param=1#?hashParam=2` it would return only the normal query params part `param=1#`, but `code` param was being matched in a hash, so it was getting `code` param from querystring, resulting in `undefined`.
Instead it should try to extract code param only from hash part (where it's originally passed).

Fixes #102 

---

Are there any links to repl site in `/repl?code=foo` format (i.e. using real query params and not hash)? If yes, this change will break them.

### CODE REVIEW

**Comment by davidchambers** [comment]
I'd like to use a query parameter here. `?v=0.22.1` seems the most appropriate way to convey this information.

**Comment by buzzdecafe** [comment]
i don't think there is any code that cares about the querystring `v`. If I visit e.g. http://ramdajs.com/repl/?v=0.19.1 I still get 

```html
<script src="//wzrd.in/standalone/ramda@latest"></script>
```

**Comment by fix-fix** [comment]
@davidchambers Links with version params will continue to work as they do now, it's only the `code` param that will be ignored.
Ok, I've read through that code and `code` param was also ignored previously, so it's safe to remove handling of `/path?code=foo` format.

I changed the commit to clarify why the hash fragment and not the query is parsed and got rid of using two sources of params (param was being checked inside `location.hash.indexOf` and `queryString.extract(location.hash)`, but they are not the same).

Do I have to commit generated `bundle.js` or it will be updated only on version bump?

**Comment by davidchambers** [comment]
Thanks so much for the fix! I'll let @buzzdecafe handle this one, as I'm not too familiar with the way the Ramda website fits together.

**Comment by buzzdecafe** [comment]
haha thanks so much! neither am i. i guess i gotta put on the hip waders and figure it out

**Comment by buzzdecafe** [comment]
perhaps i am missing something, but i don't think this is fixing the "missing code" problem? There seems to be a conflict when the user arrives with the querystring `v` set to a version number, and then the code string is appended to the hash. The querystring is set in the top nav links, although, as noted above, it is now being ignored. So there's a couple of problems to fix here:

1. resolve conflict with `v` in querystring and `code` in hash; and
2. make `v` work as it used to

**Comment by fix-fix** [comment]
I looked through the codebase history and found that dynamic loading of Ramda version was accidentally removed in #45, and I think it could be easily restored.

The first problem from your list is already solved here. I will try to fix the `v` param handling tomorrow in the same PR.

**Comment by buzzdecafe** [comment]
thanks for the research.

>  will try to fix the v param handling tomorrow in the same PR.

👍

**Comment by fix-fix** [comment]
`v` param handling changes:
* `v` URL param from query string now defines which version of Ramda will be used on the page.
* On the docs page for version `X` 'Try in REPL' button on a code snippet now opens REPL for the version `X` of Ramda (currently only works for 0.22.1+ docs, old pages have to be rebuilt to make it work)

There is now a new minor issue if different versions are allowed: in the navbar at the top of the REPL page it says 'Ramda vXXX', where 'XXX' is the latest Ramda version. It might be a little bit confusing, when user visits REPL page with old Ramda version and some new functionality doesn't work, but in the navbar it displays the latest version.
The possible fixes are:
* to remove version from the navbar
* to provide and expose the version number in the Ramda library itself and show it instead of the build target version. It's better to use version from the loaded library than the `v` param from the URL, because any garbage can be put in the URL.
* to build REPL page for each version separately the same way docs are built. I don't think this is suitable, because all the REPL pages will be the same except script URL and old URLs will be broken.

There were also some minor infrastructure changes:
* `http-server` is updated to make `npm run server` work on Windows
* `browserify` dependency is added for repl package, since it's no longer autoinstalled in npm3

Finally I rebuilt docs and repl pages in [the last commit](https://github.com/ramda/ramda.github.io/pull/103/commits/d88dbde0bce5d2011431e884c29193aa3ce826e5), but it can be dropped if you're not going to publish a new website version now.

---

Because the version of `gitbook` dependency wasn't specified directly in the package.json after fresh installation of this repo I got gitbook version v3.x instead of previously used gitbook version v2.x.
There were some changes in output file structure (location of plugin files) after building the docs and manual pages (see [commit with changes after the first run of `VERSION=... make`](https://github.com/ramda/ramda.github.io/pull/103/commits/0caa505ab0af35725ed7110d004cdcc2010311c6)) and `make` command was sometimes exiting with an error on gitbook step, but also there was some little bug fixed in the docs files (custom styles for long function on the docs page were not applied).
But I don't think `gitbook` version change should make it into this PR, and it will be conflicting with users with old package version, if v3.x version will not be defined in the package.json.

Taking argument above and argument from #107 (that there shouldn't be `/manual` files for each version at all) into consideration should I drop all the build artifacts changes from this PR, install gitbook v2.x and set this version in package config, check that everything works with v2.x and keep only changes to source files?

**Comment by buzzdecafe** [comment]
> to provide and expose the version number in the Ramda library itself and show it instead of the build target version. It's better to use version from the loaded library than the v param from the URL, because any garbage can be put in the URL.

That would be my prefernce, followed by

> to remove version from the navbar

I'm happy to merge as-is and fix the navbar in a separate PR

----------------

> Finally I rebuilt docs and repl pages in the last commit, but it can be dropped if you're not going to publish a new website version now.

Might as well publish now

**Comment by buzzdecafe** [comment]
Thanks! 🐪

**Pull request merged**
