### PR TITLE
Fixed docs

### PR DESCRIPTION
**Pull request by Andarist**
ramda/ramda#2332

### CODE REVIEW

**Comment by kedashoe** [comment]
Looks ok to me, @MattMS @buzzdecafe?

**Comment by MattMS** [comment]
What is the reason for changing from targeting the single `dist` file to the `src` folder?

Also, if we target the folder, the `jsdoc` script break once this repo is updated to 0.25.0, since the folder seems to have been renamed from `src` to `source`.

**Comment by kedashoe** [comment]
It is related to https://github.com/ramda/ramda/issues/2328. Rollup mangles some names when building `dist/ramda.js`, but we have more control over what ends up in `src` so the names should be ok.

`src` is included in the npm package, so I think we should be ok there as this points to the installed package.

It does feel a off to me though. We have been building from a file in the repo and now we are building from something that is not in vc. Should we have a script copy `node_modules/ramda/src` to somewhere in the repo?

**Comment by Andarist** [comment]
> It does feel a off to me though. We have been building from a file in the repo and now we are building from something that is not in vc. Should we have a script copy node_modules/ramda/src to somewhere in the repo?

Whatever you choose, I havent found any compelling reason myself to copy it, just for sake of copying.

Let me know what would you like me to do!

**Comment by kedashoe** [comment]
Alright I'm ok with it, can always change later if we find a reason to do so.

**Pull request merged**
