### PR TITLE
Fixes #80 Visual bug -- overflow <li> bounding box when name is too long

### LINKED ISSUE #80: Documentation: Visual bug -- overflow <li> bounding box when name is too long
overflow
behavior is consistent at smaller & larger zoom levels in chrome

### PR DESCRIPTION
**Pull request by thurt**
possible-fix

### CODE REVIEW

**Comment by buzzdecafe** [comment]
thanks! :cow2:

**Comment by thurt** [comment]
@buzzdecafe Can you tell me a little about the build process? I am confused specifically because I don't see `docs/index.handlebars.html` being used in the makefile? Do you create a static `docs/index.html` from the `handlebars` file before making a new `VERSION=x.y.z make`?

**Comment by taylonr** [comment]
There is a  publish.js inside the jsdocs folder. It renders the templates

**Comment by buzzdecafe** [comment]
yes, publish.js is used by jsdoc

**Comment by thurt** [comment]
@taylonr @buzzdecafe  Thank you! jsdoc is new to me

**Comment by buzzdecafe** [comment]
i don't think we're totally thrilled with jsdoc, but we're stuck with it now

**Comment by CrossEye** [comment]
> i don't think we're totally thrilled with jsdoc

Very dry.

**Pull request merged**
