### PR TITLE
Add 'pretty output' button

### PR DESCRIPTION
**Pull request by craigdallimore**
This adds a `Pretty Output` button next to the existing `Clear Output` button. A user can press it to attain a formatted view of their output text.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
LGTM! 🐪

**Comment by buzzdecafe** [comment]
hmmm, worked on my local but not working on live site?

**Comment by craigdallimore** [comment]
@buzzdecafe I must have missed something. Taking a look now.

**Comment by craigdallimore** [comment]
@buzzdecafe here is another PR where I have rebuilt the `bundle.js` for the repl. In hindsight  I should have checked it in ... right?

**Comment by buzzdecafe** [comment]
i think so. i am still trying to get a handle on all the moving parts.

**Pull request merged**
