### PR TITLE
Use Pug templates for index and releases pages

### PR DESCRIPTION
**Pull request by MattMS**
Pug templates seem to have better support for inheritance than Handlebars.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
i'll try and find some time to look this over soon. thanks

**Comment by MattMS** [comment]
No worries.
I mostly did it to get feedback if others are comfortable with it.

If people are happy to go ahead with it, then I will update the other templates and add the compiled HTML files.

**Comment by buzzdecafe** [comment]
apologies, too many irons in too many fires. will look presently

**Comment by MattMS** [comment]
Thanks for the update, but no need to apologise. 😄

**Comment by buzzdecafe** [comment]
ok finally i am looking at this! again my apologies. so ichecked out your branch and when i run `npm run jsdoc` i get

```
> ramda.github.io@0.23.0 jsdoc /home/mike/dev/ramda.github.io
> jsdoc --destination ./docs --template . ./docs/dist/ramda.js

FATAL: Unable to load template: Unexpected token {

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "jsdoc"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! ramda.github.io@0.23.0 jsdoc: `jsdoc --destination ./docs --template . ./docs/dist/ramda.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ramda.github.io@0.23.0 jsdoc script 'jsdoc --destination ./docs --template . ./docs/dist/ramda.js'.
npm ERR! This is most likely a problem with the ramda.github.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jsdoc --destination ./docs --template . ./docs/dist/ramda.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ramda.github.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ramda.github.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mike/dev/ramda.github.io/npm-debug.log
```

**Comment by MattMS** [comment]
I think that's unrelated, since I haven't added the Pug templates to JSDoc yet.

**Comment by buzzdecafe** [comment]
apologies, i'll clean up my repo and try again

**Comment by buzzdecafe** [comment]
Bugger, something really weird is going on here. This works fine on my laptop, but I get the error above on the desktop. Very similar to the behavior I saw in #158 , but i did a full remove and checkout and still get the error. So this is Ok with me since it is fine on the laptop

**Comment by MattMS** [comment]
That's really strange.
Do you mind sharing the differences between your desktop and laptop?
Like are they same versions of OS, Node, and Git?

**Comment by buzzdecafe** [comment]
upgraded node to 6.10 and seems to be ok now 

ಠ_ಠ

**Comment by MattMS** [comment]
That kind of makes sense, in an annoying way.
FWIW, I'm usually working on latest Node 7, but I tend not to use many new ES features if I don't need to, so I would think any Node 6 would be fine.

**Pull request merged**
