### PR TITLE
0.24 docs; works on my machine

### PR DESCRIPTION
**Pull request by buzzdecafe**
i don't know the appropriate build process for this site; had to do some manual tweaking of repl and to load the latest version. anyways, i think i got it all working

### CODE REVIEW

**Comment by kedashoe** [comment]
Me neither, would you like me to test your branch? What commands should I run?

**Comment by buzzdecafe** [comment]
yeah please pull from my branch. you ought to be able to just run `npm run server` and then poke around to make sure things look right, e.g. all the new functions are there, and repl has proper version, etc.

**Comment by kedashoe** [comment]
Looks good to me.

I played around with the build a bit. `_isArrayLike` is included because I did not remove the jsdoc documentation for it, and the script is dealing with `ramda.js` and so doesn't know anything about our `internal` folder.

I've submitted a PR to ramda to fix it, but I don't think we need to bother with another release just so we can pull the changes in here. If you just "manually" update the jsdoc info for `_isArrayLike` in /docs/dist/ramda.js to match

https://github.com/kedashoe/ramda/blob/655e61bf5b86e029a657a97f733b72a9f5ed2fec/src/internal/_isArrayLike.js

and then run the build again, you should see it go away. Let me know if it doesn't work and I'll update my PR to match whatever you do to get it to work. When we merge https://github.com/ramda/ramda/pull/2184, the fix will be included in the next release.

**Comment by buzzdecafe** [comment]
updated

**Comment by kedashoe** [comment]
:+1:

**Comment by buzzdecafe** [comment]
thx

**Pull request merged**
