### PR TITLE
Color output for "Try Ramda"

### PR DESCRIPTION
**Pull request by craigdallimore**
# Color output for "Try Ramda"

In this PR:

- `CodeMirror` is reused on the output of the "Try Ramda" repl in `readonly` mode, providing consistent syntax highlighting.
- The _Pretty Button_ and _Reset Button_ now receive a reference to the output CodeMirror object so they can call upon it's API rather than directly manipulating the DOM.
- The input and output CodeMirror instances derive their config from a common configuration object.

cm

### CODE REVIEW

**Comment by buzzdecafe** [comment]
This looks slick! I wanna clone & test your branch, but since I've got company in the house it may be a while.

**Comment by craigdallimore** [comment]
@buzzdecafe it's a perfect opportunity to introduce your guests to the joy of _ramda_.

**Comment by buzzdecafe** [comment]
joyoframda

**Comment by CrossEye** [comment]
Just seeing this.  It looks fantastic!

**Comment by buzzdecafe** [comment]
finally took a look locally. this is really nice. Thanks!

**Pull request merged**
