### PR TITLE
Fixed interference of css style from docs page to repl

### PR DESCRIPTION
**Pull request by zehua**
As discussed in https://github.com/ramda/ramda.github.io/pull/190#issuecomment-331838683, the PUG based template has some minor styling issue on the repl. This is due to the over-general css class `.repl` introduced in https://github.com/ramda/ramda.github.io/pull/185/files#diff-e73ad0a6a3cca0e9ce1279bf47761a0eR45. That PR itself is fine because `repl/index.html` did not include `style.css`. But when the PR https://github.com/ramda/ramda.github.io/pull/175/files#diff-8ca7384ffd04b23fb9f8dde4473e055fR14 refactored the repl index.pug template to inherit the same `layout.pug` which includes `style.css`, the interference of the css style takes effect.

Alt text

This PR made the css class name and selector for docs more selective to avoid messing up with the `.repl` class in the repl.

I re-generated `style.css`, but not sure if I should update the one in `0.24.1` folder or anywhere else.

@MattMS @tolmasky @buzzdecafe

### CODE REVIEW

**Comment by zehua** [comment]
ping reviewers

**Comment by zehua** [comment]
ping reviewers @MattMS @tolmasky

**Comment by tolmasky** [comment]
I'm happy to look this over, but I'm not sure if I have reviewing powers

**Comment by tolmasky** [comment]
This certainly LGTM

**Comment by buzzdecafe** [comment]
sorry i have been totally buried lately. will try to look over the weekend, please ping me again if you have heard nothing by sunday

**Comment by zehua** [comment]
@buzzdecafe ping ping

**Comment by buzzdecafe** [comment]
thanks for your patience

:cow2:

**Pull request merged**
