### PR TITLE
Inline runnable examples with RunKit

### PR DESCRIPTION
**Pull request by tolmasky**
I'd like to propose using RunKit embeds for the examples in Ramda's documentation. The main benefits over the current system are:

1. The examples are runnable inline, allowing users to stay on the main documentation page and see the documentation, etc.
2. Since it uses RunKit, when users edit the samples, they can make use of other packages as well.
3. Users can select different versions of node to see possible differences in behavior.
4. The results are presented with our nice object viewers, in particular, stack trace viewer which is particularly helpful for beginners ( http://blog.runkit.com/2017/02/01/stop-filing-bugs-file-a-container.html ).

screen shot 2017-07-04 at 10 15 32 am

I've modeled this commit after Lodash's use of RunKit for their own documentation (https://lodash.com/docs/). Namely, the embed is only loaded once "Try it in REPL" is clicked, and if for whatever reason RunKit is down, it falls back to the current behavior, so the page will never be "broken". Lodash has been using RunKit for a year now and they are quite happy with it, and express recently added RunKit for their Getting Started example as well. https://expressjs.com/en/starter/hello-world.html

### CODE REVIEW

**Comment by CrossEye** [comment]
I am all for this.  I meant to try this ages ago and never got around to it.

:100:

**Comment by buzzdecafe** [comment]
Some style tweaks may be required. Firefox Developer Edition 55.0b3 (64-bit) & Chromium 58.0.3029.110 on Ubuntu 16.04 (64-bit) both look more or less like this on my machine:

Firefox

**Comment by buzzdecafe** [comment]
this might be a simple matter of adding `width: 100%` to the `repl` iframe

**Comment by tolmasky** [comment]
This should fix it. The problem is I didn't commit the style.css that gets generated.

**Comment by kedashoe** [comment]
This is cool but I personally prefer the REPL. What do you guys think about having two links, "Try in REPL" and "Try Inline" or something like that?

**Comment by buzzdecafe** [comment]
@tolmasky i will try and get a look at the latest tonight
@kedashoe i don't have a strong feeling one way or the other. I'd be happy to offload some of the maintenance. But I am squeamish about the dependency

**Comment by CrossEye** [comment]
@kedashoe: While I do very much like our REPL, the ability to run these without leaving the page would be quite nice.  If we can do it comfortably (that is, without confusing users), then I'd be all for presenting both options.

**Comment by buzzdecafe** [comment]
Not quite dialed in yet: 

* The delay between clicking "Try in REPL" and RunKit appearing is long enough to warrant some indication to the user that work is happening. At present, a blank space appears, and after a bit, the runkit iframe loads.
* iframe is now too wide and has a horizontal scroll bar:

image

**Comment by tolmasky** [comment]
@buzzedcafe if you want to give it a shot now, there is no longer any blank in the middle of having it appear, and the scrolling should be fixed.

**Comment by kedashoe** [comment]
I was seeing same issue as @buzzdecafe , it is fixed for me now.

**Comment by kedashoe** [comment]
Could you update the PR with a UI that has a link to the REPL as well as the inline version so we can see how that looks?

**Comment by tolmasky** [comment]
Something like this maybe?

screen shot 2017-07-10 at 11 38 33 am

I'm not entirely sure how to limit the confusion here for people who aren't already familiar with the two features (its two buttons that do two subtly different things). There's some more advanced options  like a Run It button that is a drop down that lets you select "open in separate REPL" or something too, but I didn't want to start going to deep on any of this since its going to end up being more of a subjective thing, and it would probably be more useful if others who want this feature to suggest their preferred verbiage, etc.

**Comment by tolmasky** [comment]
Another option:

screen shot 2017-07-10 at 11 44 44 am

I'm also not too crazy about this one, but may make it more obvious?

**Comment by tolmasky** [comment]
@buzzedcafe @CrossEye any opinion on the direction to go ahead here? The remaining question seems to be whether to have both buttons or not. Additionally, if we want them, whether you prefer the horizontal or vertical configuration.

I believe all the technical issues have been resolved.

**Comment by kedashoe** [comment]
ping @buzzdecafe @CrossEye https://github.com/ramda/ramda.github.io/pull/185#issuecomment-314549040. My vote is for both buttons, horizontally

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by tolmasky** [comment]
OK I have committed the changes for the two buttons, and changed the words a bit which I think make the buttons better. Let me know!

**Comment by kedashoe** [comment]
Looks like the part that sets the code for the REPL is not working.

Also I prefer the wording you had first, "Open in REPL".

**Comment by tolmasky** [comment]
OK, changed the wording. I think this fixes the REPL thing, but please confirm as I've never been able to get the REPL to work locally.

**Comment by kedashoe** [comment]
Looks good to me!

Do we need the changes in the 24.1 directory? I'm not sure. @buzzdecafe ?

**Comment by buzzdecafe** [comment]
no reason why we couldn't rebuild. let's merge this thing first

**Comment by buzzdecafe** [comment]
thanks @tolmasky 
i confirmed the REPL is behaving as expected

:cow2:

**Pull request merged**
