### PR TITLE
Remove manual from version folders

### LINKED ISSUE #107: Remove manual from version folders
Considering the manual is not based on the version of Ramda, should it be removed from each of the version folders?

I'm also thinking that since it hasn't been linked from pages yet that it could be removed without breaking links.

Just to be clear, I'm not talking about removing the `manual` folder from the root of the repo.

### PR DESCRIPTION
**Pull request by MattMS**
Fixes #107

### CODE REVIEW

**Comment by buzzdecafe** [comment]
:tada: Thanks for this -- I need to fetch your branch and review on my local machine, which i plan to do tonight.

**Comment by MattMS** [comment]
No worries!
Nothing beats the feeling of deleting unnecessary code.
I'm happy you let me take the honour. 😄

**Comment by buzzdecafe** [comment]
ok -- this is *great*, thank you. Can you do one *small* thing please-- edit the Makefile so it does not publish to the version directory? These are the offending lines:

```sh
72 .PHONY: gitbook
73 gitbook: check-version
74   mkdir -p '$(VERSION)/manual'  # delete this line
75   $(GITBOOK) build manual '$(VERSION)/manual' # replace $(VERSION) with .
76   find '$(VERSION)/manual' -name '*.html' -print0 \ # replace $(VERSION) with .
77     | xargs -0 perl -p -i -e 's/ data-revision="[^"]*"//g'
78 
```

I think that would do it

**Comment by MattMS** [comment]
Done!

I can't test the Makefile to see if that still works though.
Nor do I have any idea if it was working before, for that matter.

**Comment by buzzdecafe** [comment]
LGTM, thanks
🐪

**Pull request merged**
