### PR TITLE
stop loading external script for now

### PR DESCRIPTION
**Pull request by buzzdecafe**
just to get the repl up on its feet again. not a permanent solution

### CODE REVIEW

**Comment by CrossEye** [comment]
LGTM.

**Comment by CrossEye** [comment]
After all sorts of hassles with my connection, I got a clean copy of the repo and tried to rebuild, only to get some sort of error.  Anyone with an idea what this is about?:

```shell
$ VERSION=0.22.1 make
find: `jsdoc': No such file or directory
mkdir -p '0.22.1/tmp'
curl --silent 'https://raw.githubusercontent.com/ramda/ramda/v0.22.1/README.md' >'0.22.1/tmp/README.md'
mkdir -p '0.22.1/tmp'
curl --silent 'https://raw.githubusercontent.com/ramda/ramda/v0.22.1/package.json' >'0.22.1/tmp/package.json'
mkdir -p '0.22.1/docs/dist'
curl --silent 'https://raw.githubusercontent.com/ramda/ramda/v0.22.1/dist/ramda.js' >'0.22.1/docs/dist/ramda.js'
VERSION='0.22.1' node_modules/.bin/jsdoc \
          --destination '0.22.1' \
          --template '' \
          '0.22.1/docs/dist/ramda.js'
make: *** No rule to make target `0.22.1/docs/main.js', needed by `all'.  Stop.
```

**Comment by fix-fix** [comment]
@CrossEye it seems like you don't have `jsdoc` binary in your repo node_modules dir.
Have you run `npm install` after cloning? Was there any error after `npm install` or is there any message about uninstalled dependencies after you run `npm ls`?

**Comment by CrossEye** [comment]
@fix-fix:s `npm install` ran clean.  I have jsdoc.  I know there's been a lot of work lately in this repo, and I haven't been paying close attention, so I'm hoping someone might know something about a make rule for `main.js` -- if that's what it really is.

**Comment by MattMS** [comment]
Use `npm run jsdoc` to rebuild the `/docs` folder.

It looks like the `Makefile` is still building everything in the version folders, where the npm scripts build everything at the top level, and then you use `npm run make_release` to copy the code into the folders.

**Pull request merged**
