### PR TITLE
Move fonts to top level

### PR DESCRIPTION
**Pull request by wmonk**
This is a crude implementation, but is a quick fix to get fonts working on `ramdajs.com/docs/`.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
wow that was fast. should style.css point at the root rather than the relative path? 
https://github.com/ramda/ramda.github.io/blob/344710c20de7586482151eac82d532c3cfd25365/0.21.0/style.css#L257

**Comment by wmonk** [comment]
I think, ultimately yes all the version docs should point to a root level for styling/fonts. But for now it's fine as 0.21.0 has it's own fonts directory.

This is the smallest change to enable a fix, and I wanted to make sure I wasn't manually writing to generated css files.

**Comment by buzzdecafe** [comment]
ok i'll buy that -- let's fix one problem at a time. thanks for the quick work

**Comment by wmonk** [comment]
Is there a list of issues/road map items you want to get sorted?

**Comment by CrossEye** [comment]
Thanks for the quick fix!

We really should maintain a good list of such issues, but we don't, just treating our issues log like both a working set of TODOs and a discussion forum.

**Pull request merged**
