### PR TITLE
fixes #42; back-button hack

### LINKED ISSUE #42: Browser back button does not work properly in docs
Example:
1. Visit http://ramdajs.com/0.18.0/docs/
2. Under `add` it says "See also `subtract`", so click that.
3. Click the browser back button.

**Expected result:** the page jumps back to `add`.
**Actual result:** The URL changes, but the page does not scroll.

I assume this is the result of some JavaScript controlling the links, though a cursory poke through the source doesn't reveal anything obvious.

### PR DESCRIPTION
**Pull request by buzzdecafe**

### CODE REVIEW

**Comment by davidchambers** [comment]
Who knew that `x = x` could have side effects? :stuck_out_tongue_winking_eye:

**Comment by buzzdecafe** [comment]
i know; I agree. I'm not proud of it. But I didn't wanna dive deep in there either

**Comment by davidchambers** [comment]
LGTM

_I can't bring myself to use `:deciduous_tree:`. ;)_

**Comment by buzzdecafe** [comment]
haha i understand

**Comment by CrossEye** [comment]
You knew I was already reluctantly on-board, but I'll skip the `:herb:` as well.  :wink:

**Pull request merged**
