### PR TITLE
Replace repl

### PR DESCRIPTION
**Pull request by craigdallimore**
This removes the existing REPL implementation from _Try Ramda_ and introduces one from the [ramda repl](https://github.com/ramda/repl) repo, using `cdn.rawgit.com` to provide the necessary CSS and JS bundle files.

Please note that `sanctuary` and `ramda-fantasy` are bundled. Happy to adjust this PR & that repo as necessary if we wish to serve them from `wzrd.in` CDN (or we can address separately).

### CODE REVIEW

**Comment by buzzdecafe** [comment]
this LGTM 🐪

**Comment by buzzdecafe** [comment]
((:bell:)) anyone else? this is a pretty significant change, but i'll take silence as agreement

**Comment by davidchambers** [comment]
I haven't been able to keep up with the tremendous amount of work you've been doing, @craigdallimore. Thank you! If you're happy with the changes, @buzzdecafe, let's merge them. :)

**Comment by CrossEye** [comment]
I too have been on the sidelines for this, but very happy to see all the work getting done.  I'm afraid that with out-of-town guests arriving, I won't have much time over the next few days, either.  But I trust @buzzdecafe.

... mostly.  :smiling_imp: 

Please feel free to merge.

**Comment by craigdallimore** [comment]
Thank you this is very encouraging.

By all means no rush, as @buzzdecafe points out this is a lot of change:

eeek

**Comment by buzzdecafe** [comment]
this is my favorite kind of PR -- mostly deletion!

**Comment by buzzdecafe** [comment]
uh-oh, not working on live site -- was fine on my local :-(

**Comment by craigdallimore** [comment]
I'll be able to inspect properly in a few hours. It is working on my mobile
at present.

**Pull request merged**
