### PR TITLE
Add missing R variable in example

### PR DESCRIPTION
**Pull request by igncp**

### CODE REVIEW

**Comment by davidchambers** [comment]
Thanks! Would you mind opening a pull request to update the [source][1] as well?


[1]: https://github.com/ramda/ramda/blob/master/src/defaultTo.js

**Comment by igncp** [comment]
Of course, I totally forgot, I'm on it :+1:

**Comment by igncp** [comment]
Now I notice that you may not want to change the previous versions docs, to leave them exactly as the respective source, and wait it is generated by the other repo fix. Should I close this?

**Comment by davidchambers** [comment]
I like the idea of fixing older versions of the document as well. I'd like to merge this pull request, but I'd like to ensure we've fixed the root cause before doing so.

**Comment by davidchambers** [comment]
ramda/ramda#1336

**Comment by davidchambers** [comment]
I was about to merge this pull request when I realized that it modifies the JavaScript files rather than the HTML files. I don't think we should retroactively make changes to __ramda.js__ itself.

If you're interested in updating the pull request to patch the HTML files instead, please do so. Otherwise, you could close this pull request. In either case, thanks for fixing the root cause.

**Comment by igncp** [comment]
Not problem at all if it you are ok with it. I updated the PR so now it just modifies the HTML files.

**Comment by davidchambers** [comment]
Terrific! Thanks again. :)

**Pull request merged**
