### PR TITLE
Add download ramda.js script

### PR DESCRIPTION
**Pull request by MattMS**
Implementation of download ramda.js file from GitHub, for #59.

### CODE REVIEW

**Comment by davidchambers** [comment]
Wouldn't it be simpler to add `ramda` as a dependency? There'd then be no need for a download script. Something like `cp node_modules/ramda/dist/ramda.js docs/dist` would then get the job done.

**Comment by MattMS** [comment]
Yeah it would probably be cleaner to do it that way, I was just following the way it is done in the Makefile.

I think there is also a requirement for downloading the `README.md` from the main repo, which I was thinking this code could be modified to do also.
Not sure if that makes any difference to the decision for including it though.

**Comment by davidchambers** [comment]
> I think there is also a requirement for downloading the `README.md` from the main repo

Could we get this file from `node_modules/ramda` as well?

**Comment by MattMS** [comment]
True, probably more reliable than downloading from GitHub too.

Should this be replaced with another issue to update the Makefile to use that method?

**Comment by davidchambers** [comment]
> Should this be replaced with another issue to update the Makefile to use that method?

Yes. I think so.

**Comment by MattMS** [comment]
Thinking further on this (after some time), does adding `ramda` as a dependency make the `*/docs/dist/ramda.js` files unnecessary?

If this is the case, then is it removing the self-contained nature of each of those folders?

To possibly preempt part of the answer, the other requirements in each `package.json` are not included in this repo, so it's already not fully self-contained.

I guess I'm asking to confirm that adding the `ramda` dependency and removing the files is the desired direction?

**Comment by CrossEye** [comment]
I guess I'm missing something.  The only thing that we wanted self-contained in each folder is the documentation pages (which includes a copy of `ramda.js`.)  AFAIK, what's in `package.json` doesn't matter at all.  But it's after midnight, and perhaps I'm just confused... :wink:

**Comment by MattMS** [comment]
I was probably overthinking it.
Although the `ramda.js` file could be recopied using the `package.json` install, we could still keep it in the repo.

I made pull request #86 as a start towards this.
I've also got the code to copy the `README.md` out of the installed dependency.
I'll create another pull request with that it in.

**Comment by buzzdecafe** [comment]
closed by #86

**Pull request closed without merging**
